# Generated by Django 5.0.6 on 2024-06-30 10:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='photo/%Y/%m/')),
                ('descripcion', models.TextField()),
                ('iva', models.CharField(max_length=2)),
                ('number_iva', models.DecimalField(decimal_places=2, max_digits=6)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('compare_valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.IntegerField(default=0)),
                ('sold', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
